import './style.scss'
import './blocks/dropdown/dropdown'
import './blocks/input/input'
import './blocks/date-dropdown/date-dropdown'
import './blocks/toggle/toggle'
import './blocks/like/like'
import 'jquery'
import 'air-datepicker'